debug = true
mode = "development"

[logging]
path = "/home/matt/var/log"

[database]
url = "postgres://bob:secret@localhost:5432/stocks"

[service]
host = "0.0.0.0"
port = 6000 # Overwritten by STOCKS_GRAPHQL_PORT
